error_on_unformatted = true
error_on_line_overflow = true
format_code_in_doc_comments = true
format_strings = true
use_small_heuristics = "Max"
use_field_init_shorthand = true
max_width = 100
wrap_comments = true
comment_width = 80
imports_granularity = "Module"
